Page({
    onLoad:function(option){
    },
    data:{
        src:'https://developers.weixin.qq.com/community/business'
    },
    onLoad:function(options){
    },
    onReady:function(){
    },
    onShow:function(){
    },
    onHide:function(){
    },
    onUnload:function(){
    },
    onPullDownRefresh:function(){
    },
    onReachBottom:function(){
    },
    onShareAppMessage:function(){
        return {
            title:'webview',
            path:'page/weui/example/webview/webview'
        };
    }
});
